# Loading data from SQL/JSON file

In [3]:
import pandas as pd 
import sqlite3

In [4]:
# created empty db connection
conn = sqlite3.connect("DS_DB.db")

In [1]:
import os 
os.getcwd()

'C:\\Users\\gopik'

In [20]:
ls

 Volume in drive C is OS
 Volume Serial Number is 7ADB-32F0

 Directory of C:\Users\gopik

07-10-2026  16:36    <DIR>          .
27-07-2025  18:40    <DIR>          ..
18-08-2026  16:23    <DIR>          .anaconda
30-09-2026  17:04             5,358 .bash_history
27-07-2024  13:55    <DIR>          .cache
18-08-2026  18:01    <DIR>          .conda
15-02-2025  17:06    <DIR>          .config
18-08-2026  16:33    <DIR>          .continuum
20-08-2026  07:13    <DIR>          .copilot
01-10-2026  11:59                74 .gitconfig
01-03-2024  19:22    <DIR>          .idlerc
07-10-2026  16:33    <DIR>          .ipynb_checkpoints
18-08-2026  16:36    <DIR>          .ipython
19-08-2026  07:07    <DIR>          .jupyter
01-10-2026  11:59                20 .lesshst
06-03-2025  19:40               820 .node_repl_history
28-09-2026  17:03                 0 .python_history
18-07-2023  12:19    <DIR>          .skiko
21-09-2026  16:40    <DIR>          .streamlit
01-05-2025  12:37    <DIR>          .th-client
01-10-2026  12:12             1,124 .viminfo
05-10-2026  16:31    <DIR>          .vscode
08-05-2026  19:35    <DIR>          .vscode-shared
18-08-2026  16:33    <DIR>          anaconda3
16-02-2025  13:53    <DIR>          Contacts
14-09-2026  22:31    <DIR>          CrossDevice
07-10-2026  16:36             2,191 data_json.json
06-10-2026  22:44    <DIR>          Documents
23-09-2026  08:34             1,653 Dought.ipynb
07-10-2026  16:23    <DIR>          Downloads
07-10-2026  16:27           937,984 DS_DB.db
21-09-2026  16:21    <DIR>          DS_projects
16-02-2025  13:53    <DIR>          Favorites
07-10-2026  16:23           807,395 layoffs.csv
16-02-2025  13:53    <DIR>          Links
16-02-2025  13:53    <DIR>          Music
07-10-2026  15:17    <DIR>          OneDrive
20-08-2026  07:13             3,798 practice1.ipynb
19-08-2026  17:49             5,231 practice2.ipynb
20-08-2026  07:22             2,693 practice3.ipynb
23-08-2026  22:10             3,122 practice4.ipynb
23-08-2026  22:54             1,873 practice5.ipynb
24-08-2026  22:23             4,269 practice6.ipynb
27-08-2026  11:10             2,399 practice7.ipynb
05-10-2026  17:35             1,515 pytest.ipynb
04-10-2026  14:01             7,972 python10.ipynb
04-10-2026  14:48            10,203 python11.ipynb
02-09-2026  17:43            16,512 python12.ipynb
03-09-2026  17:41             9,452 python13.ipynb
04-09-2026  17:40             3,313 python14.ipynb
05-09-2026  17:46             6,301 python15.ipynb
04-10-2026  17:10            12,079 python16.ipynb
04-10-2026  17:23             9,396 python17.ipynb
23-09-2026  08:26             5,712 python18.ipynb
21-09-2026  15:35               617 python19.ipynb
18-08-2026  18:01             9,464 python2.ipynb
21-09-2026  15:35            12,926 python20.ipynb
15-09-2026  17:40            10,320 python21.ipynb
17-09-2026  17:10             3,459 python22.ipynb
18-09-2026  17:50             5,402 python23.ipynb
19-09-2026  17:49            10,157 python24.ipynb
29-09-2026  16:49             2,092 python25.ipynb
30-09-2026  17:49               895 python26.ipynb
03-10-2026  16:54             1,824 python27.ipynb
07-10-2026  16:36            40,380 python28.ipynb
04-10-2026  12:18             6,489 python4.ipynb
04-10-2026  12:30             6,645 python5.ipynb
04-10-2026  12:34             5,137 python6.ipynb
26-08-2026  17:25             4,791 python7.ipynb
02-09-2026  11:31             6,284 python8.ipynb
29-08-2026  17:52             5,247 python9.ipynb
24-01-2026  17:31    <DIR>          Saved Games
16-02-2025  13:53    <DIR>          Searches
19-09-2026  17:15                16 test_file.txt
19-09-2026  17:49                 5 test_file1.txt
22-08-2026  16:11                14 untitled.py
16-02-2025  13:53    <DIR>          Videos
              47 File(s)      1,994,623 bytes
              30 Dir(s)  363,604,987,904 bytes free

In [11]:
df = pd.read_csv("layoffs.csv")
df

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Blaize,SF Bay Area,NaN,9/30/2026,0.260,AI,https://www.tradingview.com/news/seekingalpha:...,Post-IPO,307.0,United States,10/1/2026
1,Workday,SF Bay Area,525.0,9/29/2026,0.025,HR,https://seekingalpha.com/news/4648205-workday-...,Post-IPO,230.0,United States,10/1/2026
2,Thinkific,"Vancouver, Non-U.S.",96.0,9/23/2026,NaN,Education,https://investors.thinkific.com/2026-09-23-Thi...,Post-IPO,22.0,Canada,9/24/2026
3,Intel,Sacramento,52.0,9/23/2026,NaN,Hardware,https://www.kron4.com/news/technology-ai/intel...,Post-IPO,12.0,United States,9/23/2026
4,Microsoft,Seattle,500.0,9/22/2026,NaN,Other,https://www.businessinsider.com/microsoft-star...,Post-IPO,1.0,United States,9/23/2026
...,...,...,...,...,...,...,...,...,...,...,...
4613,Service,Los Angeles,NaN,3/16/2020,1.000,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4614,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.100,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4615,Panda Squad,SF Bay Area,6.0,3/13/2020,0.750,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4616,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.400,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4617,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

In [13]:
# Storing data into db
df.to_sql("table1", conn, if_exists ="replace")

4618

In [15]:
df1 = pd.read_sql(" Select * from table1", conn)
df1

,index,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,0,Blaize,SF Bay Area,NaN,9/30/2026,0.260,AI,https://www.tradingview.com/news/seekingalpha:...,Post-IPO,307.0,United States,10/1/2026
1,1,Workday,SF Bay Area,525.0,9/29/2026,0.025,HR,https://seekingalpha.com/news/4648205-workday-...,Post-IPO,230.0,United States,10/1/2026
2,2,Thinkific,"Vancouver, Non-U.S.",96.0,9/23/2026,NaN,Education,https://investors.thinkific.com/2026-09-23-Thi...,Post-IPO,22.0,Canada,9/24/2026
3,3,Intel,Sacramento,52.0,9/23/2026,NaN,Hardware,https://www.kron4.com/news/technology-ai/intel...,Post-IPO,12.0,United States,9/23/2026
4,4,Microsoft,Seattle,500.0,9/22/2026,NaN,Other,https://www.businessinsider.com/microsoft-star...,Post-IPO,1.0,United States,9/23/2026
...,...,...,...,...,...,...,...,...,...,...,...,...
4613,4613,Service,Los Angeles,NaN,3/16/2020,1.000,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4614,4614,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.100,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4615,4615,Panda Squad,SF Bay Area,6.0,3/13/2020,0.750,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4616,4616,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.400,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4617,4617,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

In [24]:
# Loading & storing from data frame
# import json
# import pandas as pd

# with open("data_json.json", "r") as f:
#     data = json.load(f)

# df2 = pd.DataFrame(data)
# df2
# df2 = pd.read_json("data_json.json")
# df2
import pandas as pd

df2 = pd.read_json("data_json.json")

df2

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [31]:
df.shape # Shape rows & cols of data frame
df.head(6) # 1 - 5 rows in pandas deafult
df.tail() # return bottom 5 records

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
4613,Service,Los Angeles,NaN,3/16/2020,1.00,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4614,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.10,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4615,Panda Squad,SF Bay Area,6.0,3/13/2020,0.75,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4616,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.40,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4617,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

In [34]:
print(df.company)
df['location']

0              Blaize
1             Workday
2           Thinkific
3               Intel
4           Microsoft
            ...
4613          Service
4614     HopSkipDrive
4615      Panda Squad
4616    Tamara Mellon
4617         EasyPost
Name: company, Length: 4618, dtype: str

0               SF Bay Area
1               SF Bay Area
2       Vancouver, Non-U.S.
3                Sacramento
4                   Seattle
               ...
4613            Los Angeles
4614            Los Angeles
4615            SF Bay Area
4616            Los Angeles
4617         Salt Lake City
Name: location, Length: 4618, dtype: str

In [36]:
# print multiple cols
df[['company','location']]

            company             location
0            Blaize          SF Bay Area
1           Workday          SF Bay Area
2         Thinkific  Vancouver, Non-U.S.
3             Intel           Sacramento
4         Microsoft              Seattle
...             ...                  ...
4613        Service          Los Angeles
4614   HopSkipDrive          Los Angeles
4615    Panda Squad          SF Bay Area
4616  Tamara Mellon          Los Angeles
4617       EasyPost       Salt Lake City

[4618 rows x 2 columns]

In [45]:
# renaming in dataframe

df = df.rename(columns = {'company ': 'industry', 'location':'uru'})
df

,company,uru,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Blaize,SF Bay Area,NaN,9/30/2026,0.260,AI,https://www.tradingview.com/news/seekingalpha:...,Post-IPO,307.0,United States,10/1/2026
1,Workday,SF Bay Area,525.0,9/29/2026,0.025,HR,https://seekingalpha.com/news/4648205-workday-...,Post-IPO,230.0,United States,10/1/2026
2,Thinkific,"Vancouver, Non-U.S.",96.0,9/23/2026,NaN,Education,https://investors.thinkific.com/2026-09-23-Thi...,Post-IPO,22.0,Canada,9/24/2026
3,Intel,Sacramento,52.0,9/23/2026,NaN,Hardware,https://www.kron4.com/news/technology-ai/intel...,Post-IPO,12.0,United States,9/23/2026
4,Microsoft,Seattle,500.0,9/22/2026,NaN,Other,https://www.businessinsider.com/microsoft-star...,Post-IPO,1.0,United States,9/23/2026
...,...,...,...,...,...,...,...,...,...,...,...
4613,Service,Los Angeles,NaN,3/16/2020,1.000,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4614,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.100,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4615,Panda Squad,SF Bay Area,6.0,3/13/2020,0.750,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4616,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.400,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4617,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

In [51]:
# Add a new colmn to dataset
# rank() func provide the rank based upon the salary
# lower funds_raised = lower rank

df['rank']= df.funds_raised.rank()
# df['rank']= df.funds_raised.rank(ascending  = false) # Using of ascending 
df
df.sort_values('rank')

# if column already present update 
# if clmn don't present it creates new column

,company,uru,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added,rank
4411,Rock Content,"Belo Horizonte, Non-U.S.",100.0,4/6/2020,0.20,Marketing,"https://link.estadao.com.br/noticias/inovacao,...",Series A,0.7000,Brazil,4/6/2020,1.0
4036,Eatsy,"Singapore, Non-U.S.",20.0,8/8/2020,1.00,Food,https://www.businesstimes.com.sg/garage/food-o...,Seed,0.9755,Singapore,8/10/2020,2.0
4295,Movidesk,"Blumenau, Non-U.S.",33.0,4/20/2020,0.25,Support,https://scinova.com.br/demissoes-a-conta-da-co...,Seed,1.0000,Brazil,4/27/2020,27.0
21,Hale,"Berlin, Non-U.S.",NaN,9/3/2026,1.00,Healthcare,https://femtechinsider.com/pelvic-pain-startup...,Seed,1.0000,Germany,9/4/2026,27.0
3433,Classkick,Chicago,NaN,8/1/2022,NaN,Education,https://docs.google.com/spreadsheets/d/1u-P5qz...,Seed,1.0000,United States,8/10/2022,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4579,Takl,Nashville,130.0,3/24/2020,NaN,Consumer,https://www.bizjournals.com/nashville/news/202...,Unknown,NaN,United States,4/2/2020,NaN
4583,Flowr,"Toronto, Non-U.S.",NaN,3/24/2020,0.25,Retail,https://www.benzinga.com/markets/cannabis/20/0...,Unknown,NaN,Canada,3/28/2020,NaN
4590,Drip,Salt Lake City,20.0,3/23/2020,NaN,Marketing,LinkedIn,Acquired,NaN,United States,4/1/2020,NaN
4604,Ejento,SF Bay Area,84.0,3/19/2020,1.00,Recruiting,https://layoffs.fyi/list/ejento/,Unknown,NaN,United States,3/28/2020,NaN
4609,Tuft & Needle,Phoenix,NaN,3/19/2020,NaN,Retail,https://www.theverge.com/2020/3/19/21185840/tu...,Acquired,NaN,United States,4/5/2020,NaN

# Delete the cols in df

In [54]:
df = df.drop(['rank'], axis = 1)  # Here axis = 1 is deleting column / 0 is deleting row
df

KeyError: "['rank'] not found in axis"

In [55]:
df

,company,uru,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Blaize,SF Bay Area,NaN,9/30/2026,0.260,AI,https://www.tradingview.com/news/seekingalpha:...,Post-IPO,307.0,United States,10/1/2026
1,Workday,SF Bay Area,525.0,9/29/2026,0.025,HR,https://seekingalpha.com/news/4648205-workday-...,Post-IPO,230.0,United States,10/1/2026
2,Thinkific,"Vancouver, Non-U.S.",96.0,9/23/2026,NaN,Education,https://investors.thinkific.com/2026-09-23-Thi...,Post-IPO,22.0,Canada,9/24/2026
3,Intel,Sacramento,52.0,9/23/2026,NaN,Hardware,https://www.kron4.com/news/technology-ai/intel...,Post-IPO,12.0,United States,9/23/2026
4,Microsoft,Seattle,500.0,9/22/2026,NaN,Other,https://www.businessinsider.com/microsoft-star...,Post-IPO,1.0,United States,9/23/2026
...,...,...,...,...,...,...,...,...,...,...,...
4613,Service,Los Angeles,NaN,3/16/2020,1.000,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4614,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.100,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4615,Panda Squad,SF Bay Area,6.0,3/13/2020,0.750,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4616,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.400,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4617,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

# Replace the value in df

In [60]:
# Replace 1 value in df
df.uru= df.uru.replace('SF Bay Area', "Hyderabad")
df
# Replace mul values in df
df.uru = df.uru.replace({'Sacramento	': "Bombay",'Seattle': "Delhi"} )
df

,company,uru,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Blaize,Hyderabad,NaN,9/30/2026,0.260,AI,https://www.tradingview.com/news/seekingalpha:...,Post-IPO,307.0,United States,10/1/2026
1,Workday,Hyderabad,525.0,9/29/2026,0.025,HR,https://seekingalpha.com/news/4648205-workday-...,Post-IPO,230.0,United States,10/1/2026
2,Thinkific,"Vancouver, Non-U.S.",96.0,9/23/2026,NaN,Education,https://investors.thinkific.com/2026-09-23-Thi...,Post-IPO,22.0,Canada,9/24/2026
3,Intel,Sacramento,52.0,9/23/2026,NaN,Hardware,https://www.kron4.com/news/technology-ai/intel...,Post-IPO,12.0,United States,9/23/2026
4,Microsoft,Delhi,500.0,9/22/2026,NaN,Other,https://www.businessinsider.com/microsoft-star...,Post-IPO,1.0,United States,9/23/2026
...,...,...,...,...,...,...,...,...,...,...,...
4613,Service,Los Angeles,NaN,3/16/2020,1.000,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4614,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.100,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4615,Panda Squad,Hyderabad,6.0,3/13/2020,0.750,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4616,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.400,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4617,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

In [61]:
# data types 
df.dtypes

company                    str
uru                        str
total_laid_off         float64
date                       str
percentage_laid_off    float64
industry                   str
source                     str
stage                      str
funds_raised           float64
country                    str
date_added                 str
dtype: object

In [67]:
# convert one dtype to another
df.total_laid_off= df.total_laid_off.astype('string')

# columns names from df
df.columns

# print only categorical colmn names  -> strings
df.select_dtypes(include = ['object', 'string']).columns

Index(['company', 'uru', 'total_laid_off', 'date', 'industry', 'source',
       'stage', 'country', 'date_added'],
      dtype='str')

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4618 entries, 0 to 4617
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4618 non-null   str
 1   uru                  4617 non-null   str
 2   total_laid_off       3016 non-null   string
 3   percentage_laid_off  2890 non-null   float64
 4   industry             4616 non-null   str
 5   stage                4610 non-null   str
 6   country              4616 non-null   str
dtypes: float64(1), str(5), string(1)
memory usage: 478.3 KB

In [69]:
 df = df.drop(['date_added','funds_raised','source','date'], axis = 1)

In [79]:
# Unique elements in df
# Count the elements 
df.industry.unique()
df.industry.value_counts()
df.groupby('industry').country.value_counts()

industry  country
AI        United States     15
          India              7
          Israel             5
          United Kingdom     3
          Germany            2
                            ..
Travel    Singapore          3
          Indonesia          3
          Israel             1
          Hong Kong          1
          Myanmar            1
Name: count, Length: 436, dtype: int64