# Handling inconsistent data with Pandas

In [12]:

import pandas as pd

df = pd.read_excel(
    r"C:\Users\MAHESH\Desktop\fullstack-python-training\Excel_data.xlsx"
)

print(df)

# c:\Users\MAHESH\Desktop\fullstack-python-training\Excel_data.xlsx

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [13]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='str')

In [17]:
# make the column name consistent
# make all the column name start with capital letter

df.colums=df.columns.str.lower()

In [18]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='str')

In [19]:
df.Name.unique()

<StringArray>
[   'olivia', 'sophia   ',      'jake',     'Rocky',      'Jake',    'Olivia',
      'John',  'Sherlock',     'Alice',  'Mr. Bean',    'Sophia',      'Liam',
      'Emma']
Length: 13, dtype: str

In [20]:
df.Name=df.Name.str.lower()

In [21]:
df.Name.unique()

<StringArray>
[   'olivia', 'sophia   ',      'jake',     'rocky',      'john',  'sherlock',
     'alice',  'mr. bean',    'sophia',      'liam',      'emma']
Length: 11, dtype: str

In [22]:
# str.strip() remove the extra spaces from the string
df.Name=df.Name.str.strip()

In [23]:
df.Name.unique()

<StringArray>
[  'olivia',   'sophia',     'jake',    'rocky',     'john', 'sherlock',
    'alice', 'mr. bean',     'liam',     'emma']
Length: 10, dtype: str

In [24]:
df.Profession.unique()

<StringArray>
[          'Teacher',       '      Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

# Data Transformation using apply() function & map() function

In [ ]:
# apply() : this functionis used to excute lambda function 
# Lambda function is one line function
# if you want to apply lambda function on a column then you can use apply() function

In [25]:
df1=df.copy()

In [27]:
# on the festival occation : sai ram decide to double the employee salary
df

      ID      Name   Age         Profession  salary  Marriage_proposal_count
0      1    olivia  23.0            Teacher  184518                        0
1      2    sophia  20.0              Boxer  119572                        2
2      3      jake  38.0          Scientist  174897                        1
3      4     rocky  56.0               Chef  117920                        2
4      4     rocky  56.0               Chef  117920                        1
..   ...       ...   ...                ...     ...                      ...
495  496      john  45.0              Boxer  137929                        0
496  497  sherlock  46.0              Boxer   39870                        6
497  498  sherlock  47.0          Detective  165951                        5
498  499    olivia  55.0           Comedian  192618                        5
499  500  sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [29]:
df1.salary=df1.salary.apply(lambda x:x*2)
df1

      ID      Name   Age         Profession  salary  Marriage_proposal_count
0      1    olivia  23.0            Teacher  369036                        0
1      2    sophia  20.0              Boxer  239144                        2
2      3      jake  38.0          Scientist  349794                        1
3      4     rocky  56.0               Chef  235840                        2
4      4     rocky  56.0               Chef  235840                        1
..   ...       ...   ...                ...     ...                      ...
495  496      john  45.0              Boxer  275858                        0
496  497  sherlock  46.0              Boxer   79740                        6
497  498  sherlock  47.0          Detective  331902                        5
498  499    olivia  55.0           Comedian  385236                        5
499  500  sherlock  59.0  Software Engineer  389772                       28

[500 rows x 6 columns]

In [32]:
# Create a new column Bonus or NO Bonus
df1["Diwali_gift"]=df1.apply(lambda row: "Bonus" if row['salary']> 100000 else "No Bonus", axis=1)

In [33]:
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count,Diwali_gift
0,1,olivia,23.0,Teacher,369036,0,Bonus
1,2,sophia,20.0,Boxer,239144,2,Bonus
2,3,jake,38.0,Scientist,349794,1,Bonus
3,4,rocky,56.0,Chef,235840,2,Bonus
4,4,rocky,56.0,Chef,235840,1,Bonus
...,...,...,...,...,...,...,...
495,496,john,45.0,Boxer,275858,0,Bonus
496,497,sherlock,46.0,Boxer,79740,6,No Bonus
497,498,sherlock,47.0,Detective,331902,5,Bonus
498,499,olivia,55.0,Comedian,385236,5,Bonus
499,500,sherlock,59.0,Software Engineer,389772,28,Bonus

In [ ]:
# Create a new column Bonus or NO Bonus
# apply() function is used to apply the lambda function on the row of the dataframe
df1["Diwali_gift"]=df1.apply(lambda row: "Bonus" if (row['salary']<300000 and row['Age']> 40) else "No Bonus", axis=1)

In [35]:
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count,Diwali_gift
0,1,olivia,23.0,Teacher,369036,0,No Bonus
1,2,sophia,20.0,Boxer,239144,2,No Bonus
2,3,jake,38.0,Scientist,349794,1,No Bonus
3,4,rocky,56.0,Chef,235840,2,Bonus
4,4,rocky,56.0,Chef,235840,1,Bonus
...,...,...,...,...,...,...,...
495,496,john,45.0,Boxer,275858,0,Bonus
496,497,sherlock,46.0,Boxer,79740,6,Bonus
497,498,sherlock,47.0,Detective,331902,5,No Bonus
498,499,olivia,55.0,Comedian,385236,5,No Bonus
499,500,sherlock,59.0,Software Engineer,389772,28,No Bonus

# map() function

In [ ]:
# map(): this function is used for element wise operation on a column of dataframe

In [36]:
df.Profession.unique()

<StringArray>
[          'Teacher',       '      Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

In [43]:
map_dict={
    'Techer':'Guruvu',
    'Boxer':'Peddi',
    'scientist':'Vignani',
    'Chef':'Ruchi',
    'Doctor':'Vaidya',
    'Artist':'Chitrakar',
    'Comdian':'Hasya',
    'Software Engineer':'Kulodu',
    'Detective':'Goppa',
    'Pilot':'Vimana'
}

In [45]:
df['Profession_new']=df.Profession.map(map_dict)
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,Profession_new
0,1,olivia,23.0,Teacher,184518,0,NaN
1,2,sophia,20.0,Boxer,119572,2,NaN
2,3,jake,38.0,Scientist,174897,1,NaN
3,4,rocky,56.0,Chef,117920,2,Ruchi
4,4,rocky,56.0,Chef,117920,1,Ruchi
...,...,...,...,...,...,...,...
495,496,john,45.0,Boxer,137929,0,NaN
496,497,sherlock,46.0,Boxer,39870,6,NaN
497,498,sherlock,47.0,Detective,165951,5,Goppa
498,499,olivia,55.0,Comedian,192618,5,NaN
499,500,sherlock,59.0,Software Engineer,194886,28,Kulodu

#  Aggregation and Grouping Function

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    str
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    str
 4   salary                   500 non-null    int64
 5   Marriage_proposal_count  500 non-null    int64
 6   Profession_new           296 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 27.5 KB

In [ ]:
# sum the total salary of all the employees
df.salary.sum()

np.int64(57801414)

In [ ]:
# Avarage salary of all the employees
# mean=sum(all elements)/total number of elements
df.salary.mean()

np.float64(115602.828)

In [50]:
# Median: Middle value after sorting the data
df.salary.median()

np.float64(117920.0)

In [53]:
# Mode: Most frequently occuring value in the data
# Mode works with categorical data and numerical data with repeated values
df.salary.mode()
df.Profession.mode()

0    Chef
Name: Profession, dtype: str

In [54]:
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [55]:
# Maximum salary of all the employees
df.salary.max()

np.int64(199529)

In [56]:
# Variance: Variance is the measure of how far a set of numbers are spread out from their average value.
df.salary.var()

np.float64(2440791463.465347)

In [57]:
df.salary.std() # Standard deviation is the square root of variance

np.float64(49404.36684611338)