In [2]:
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [3]:
df.Profession.unique()

<ArrowStringArray>
[          'Teacher',       '      Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

In [4]:
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [7]:
# Statastical information
df.describe()

# How value far from mean 
# mean -> avg
# percentile : from how many i on ahead
# df.info()

               ID         Age         salary  Marriage_proposal_count
count  500.000000  492.000000     500.000000                500.00000
mean   250.458000   40.810976  115602.828000                  4.02600
std    144.552978   11.790553   49404.366846                  5.25362
min      1.000000   20.000000   30164.000000                  0.00000
25%    125.750000   31.000000   74964.750000                  1.00000
50%    250.500000   40.500000  117920.000000                  3.00000
75%    375.250000   51.000000  160579.500000                  5.00000
max    500.000000   60.000000  199529.000000                 40.00000

In [11]:
# describing categorical cols
df.describe(include = 'object')

C:\Users\gopik\AppData\Local\Temp\ipykernel_13404\2955637720.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = 'object')

            Name Profession
count        500        500
unique        13         10
top     Sherlock       Chef
freq          61         58

In [14]:
df.Profession.unique()
df.Profession.value_counts()
df.Name.value_counts()

Name
Sherlock     61
Emma         57
John         55
Alice        53
Mr. Bean     52
Olivia       50
Jake         47
Rocky        44
Sophia       41
Liam         37
olivia        1
sophia        1
jake          1
Name: count, dtype: int64

# ** Filtering & Idexing

In [24]:
# Query : find those records where salary >100000
df[(df.salary > 50000) & (df.salary < 100000)]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
10    11     Rocky   NaN             Doctor   75543                        5
15    16  Sherlock  30.0              Boxer   57774                        0
23    24  Sherlock  42.0              Boxer   92995                        2
26    27     Alice  48.0              Pilot   99949                        4
28    29     Alice  21.0               Chef   84792                        3
..   ...       ...   ...                ...     ...                      ...
479  480      Liam  26.0              Pilot   80708                        3
481  482    Olivia  56.0  Software Engineer   71404                        5
487  488  Sherlock  49.0              Pilot   82386                        2
488  489      Emma  21.0  Software Engineer   92013                        2
492  493      John  55.0             Artist   57720                        2

[132 rows x 6 columns]

In [26]:
# Query : find those records where salary < 500000 or salary >150000 
df[(df.salary < 50000) | (df.salary < 100000)]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
10    11     Rocky   NaN             Doctor   75543                        5
13    14      John  46.0             Artist   43078                       12
15    16  Sherlock  30.0              Boxer   57774                        0
23    24  Sherlock  42.0              Boxer   92995                        2
26    27     Alice  48.0              Pilot   99949                        4
..   ...       ...   ...                ...     ...                      ...
488  489      Emma  21.0  Software Engineer   92013                        2
489  490      John  56.0          Scientist   41192                        7
492  493      John  55.0             Artist   57720                        2
494  495     Rocky  27.0             Doctor   46975                        0
496  497  Sherlock  46.0              Boxer   39870                        6

[196 rows x 6 columns]

In [43]:
# Query : find max salary 
df[df.salary == df.salary.max()]
# max salary 
df[df.Marriage_proposal_count == df.Marriage_proposal_count.max()]
df[df.salary == df.salary.min()][['Name', 'Profession']]
df.loc[df['salary'] == df['salary'].min()][['Name','Profession']]

         Name Profession
213  Sherlock       Chef

# ** Indexing

In [45]:
# loc -> filtering fixed number of indexes
df.loc[1:6, 'Name':'Profession']

        Name   Age   Profession
1  sophia     20.0        Boxer
2       jake  38.0    Scientist
3      Rocky  56.0         Chef
4      Rocky  56.0         Chef
5      Rocky  56.0         Chef
6      Rocky  56.0         Chef

In [52]:
df.loc[10 : 20, 'Age':'salary']
df.loc[10 : 20 : 2, ['Age','salary']]

     Age  salary
10   NaN   75543
12  22.0  102063
14  40.0  171553
16  46.0  135907
18  25.0  181312
20  40.0  118998

In [53]:
# iloc -> index based fetching

# Query : printrecord from 1 to 6 and columns from 1 to 3
# df.iloc[row,col]
df.iloc[1:7, 1:4]

        Name   Age   Profession
1  sophia     20.0        Boxer
2       jake  38.0    Scientist
3      Rocky  56.0         Chef
4      Rocky  56.0         Chef
5      Rocky  56.0         Chef
6      Rocky  56.0         Chef

In [ ]:
# Interv Questions

# Diff b/w loc & iloc
# loc we need to mention the index of columns
# while in iloc we mention index of columns

# iloc goes upto n-1, but loc goes upto nth value

# iloc is little faster than loc bec loc needs to convert colmns to index
#

In [54]:
# at & iat

df.at[0,'Name']

'olivia'

In [55]:
df.iat[0,1]

'olivia'

In [ ]:
# at & iat are used specifically to access the single value / element