In [ ]:
# Null:- th info which is not provided
# NaN:- Not a number
# na
# Null /na vs 0
# 0 is a value but null is not a value

# Handling Null Values

In [ ]:

import pandas as pd

df = pd.read_excel(
    r"C:\Users\MAHESH\Desktop\fullstack-python-training\11_Pandas\Excel_data.xlsx"
)

df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [8]:
df.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [9]:
df.isna().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [11]:
df[df.Age.isnull()]

    ID      Name  Age         Profession  salary  Marriage_proposal_count
10  11     Rocky  NaN             Doctor   75543                        5
11  12      Jake  NaN             Artist  174780                        5
45  46      Liam  NaN             Doctor   84583                        0
46  47  Mr. Bean  NaN             Artist  190559                        5
71  72      Emma  NaN              Pilot   49986                        3
72  73    Sophia  NaN             Artist   86741                        1
73  74     Rocky  NaN  Software Engineer  159260                        0
74  75  Sherlock  NaN          Detective  165463                        0

In [12]:
#  delete the records which having null values
df1=df.copy()
df1.dropna(inplace=True)

In [13]:
df1.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [14]:
df1.shape

(492, 6)

In [15]:
# We need too handle null values
# Ans:-  in-bult funcation might not working properly like std(), .means()
# pandas funcs can work but still give ans as it will not include the Nan values
import numpy as np
vals=[10,20,40,50,np.nan]
print(np.std(vals))
sum(vals)/len(vals)

nan

nan

In [16]:
df.Age.mean()

np.float64(40.8109756097561)

In [17]:
ser1=pd.Series(vals)
ser1.mean()

np.float64(30.0)

In [18]:
# Approach1 :- delete the records which having null values
# Approach2:- delete the column which having null values

df2=df.copy()

In [ ]:
# axis=1:- delete the columnn which is having null values
# axis=0:- delete the row which is having null values
# how='any' :- if any null value is there then delete the column
# how='all' :- if all values are null then delete the column
df2=df2.dropna(axis=1, how='any')
df2.isnull

<bound method DataFrame.isnull of       ID       Name         Profession  salary  Marriage_proposal_count
0      1     olivia            Teacher  184518                        0
1      2  sophia                 Boxer  119572                        2
2      3       jake          Scientist  174897                        1
3      4      Rocky               Chef  117920                        2
4      4      Rocky               Chef  117920                        1
..   ...        ...                ...     ...                      ...
495  496       John              Boxer  137929                        0
496  497   Sherlock              Boxer   39870                        6
497  498   Sherlock          Detective  165951                        5
498  499     Olivia           Comedian  192618                        5
499  500   Sherlock  Software Engineer  194886                       28

[500 rows x 5 columns]>

In [21]:
df2=df2.dropna(axis=1, how='all')
df2.isnull().sum()

ID                         0
Name                       0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [22]:
df3=df.copy()

In [ ]:
# fillna() ffunction is used to fill the null values with some other value
df3.Age=df3.Age.fillna(18)

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [25]:
df3.shape

(500, 6)

In [26]:
av=df.Age.mean()
av

np.float64(40.8109756097561)

In [27]:
df.Age=df.Age.fillna(av)

In [28]:
df.Age.isnull().sum()

np.int64(0)

# Handling the Duplicates Values

In [29]:
# Identify the duplicates records
df.duplicated().sum()

np.int64(3)

In [32]:
# show the duplicate records
df[df.duplicated()]

   ID   Name   Age Profession  salary  Marriage_proposal_count
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [ ]:
# keep=False will show all the duplicate records
# keep=true will show only the last duplicate record
df[df.duplicated(keep=False)]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [34]:
df[df.duplicated(keep='last')]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2

In [35]:
# deleting the duplicate records
df=df.drop_duplicates()