# Movies Dataset: Pandas Practice Queries

This notebook answers 20 Pandas practice queries using `Movies_Dataset.xlsx`. Each section is independent and can be run after the setup cell.

## Setup and data loading

The workbook contains the columns `Movie Name`, `Genre`, `Release_Year`, `IMDb_Rating`, and `Revenue`. Revenue values are treated as the dataset's box-office collection measure.

In [23]:
from pathlib import Path
import pandas as pd

DATA_FILE = Path(r"C:\Users\MAHESH\Desktop\fullstack-python-training\Movies_Dataset.xlsx")
df = pd.read_excel(DATA_FILE)

# Keep the original data unchanged; later transformation queries use copies.
df.head()

  Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0    Movie 1     Sci-Fi          2000          6.0  1680.53
1    Movie 2  Adventure          2000          2.2   987.24
2    Movie 3    Romance          2002          5.2  1122.13
3    Movie 4    Romance          2001          4.5   581.84
4    Movie 5     Action          2012          6.6  1205.51

In [24]:
# Quick inspection
print(f"Rows: {len(df):,}")
print(f"Columns: {list(df.columns)}")
df.info()

Rows: 1,000
Columns: ['Movie Name', 'Genre', 'Release_Year', 'IMDb_Rating', 'Revenue']
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie Name    1000 non-null   str
 1   Genre         1000 non-null   str
 2   Release_Year  1000 non-null   int64
 3   IMDb_Rating   1000 non-null   float64
 4   Revenue       1000 non-null   float64
dtypes: float64(2), int64(1), str(2)
memory usage: 39.2 KB

## 1. Select all movies in the Action genre

In [25]:
action_movies = df[df["Genre"].eq("Action")]
action_movies

    Movie Name   Genre  Release_Year  IMDb_Rating  Revenue
4      Movie 5  Action          2012          6.6  1205.51
34    Movie 35  Action          2009          8.7   545.60
64    Movie 65  Action          2023          7.7  1137.79
65    Movie 66  Action          1999          3.1  1335.85
73    Movie 74  Action          2001          4.1   350.80
..         ...     ...           ...          ...      ...
930  Movie 931  Action          1994          8.6  1863.66
944  Movie 945  Action          2004          7.5  1709.81
980  Movie 981  Action          2022          5.2    28.40
988  Movie 989  Action          2023          4.1   231.67
998  Movie 999  Action          1996          8.9   941.67

[104 rows x 5 columns]

## 2. Select movies released after 2000

In [26]:
movies_after_2000 = df[df["Release_Year"] > 2000]
movies_after_2000

    Movie Name     Genre  Release_Year  IMDb_Rating  Revenue
2      Movie 3   Romance          2002          5.2  1122.13
3      Movie 4   Romance          2001          4.5   581.84
4      Movie 5    Action          2012          6.6  1205.51
6      Movie 7   Mystery          2021          5.1  1683.99
7      Movie 8    Comedy          2005          4.0  1062.13
..         ...       ...           ...          ...      ...
988  Movie 989    Action          2023          4.1   231.67
989  Movie 990   Fantasy          2004          1.6  1056.58
991  Movie 992  Thriller          2004          9.2   251.25
995  Movie 996    Sci-Fi          2013          8.7   456.39
997  Movie 998   Fantasy          2016          8.1  1161.96

[518 rows x 5 columns]

## 3. Select movies with an IMDb rating greater than 8.5

In [27]:
high_rated_movies = df[df["IMDb_Rating"] > 8.5]
high_rated_movies

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
34     Movie 35     Action          2009          8.7   545.60
51     Movie 52    Mystery          1998          9.0  1089.93
56     Movie 57     Comedy          1993          9.2  1586.13
74     Movie 75  Adventure          1999          8.6  1688.49
81     Movie 82    Mystery          1997          8.6  1238.32
..          ...        ...           ...          ...      ...
991   Movie 992   Thriller          2004          9.2   251.25
992   Movie 993     Horror          1985          9.6   951.23
995   Movie 996     Sci-Fi          2013          8.7   456.39
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[148 rows x 5 columns]

## 4. Select only Movie Name and Genre columns

In [28]:
movie_names_and_genres = df[["Movie Name", "Genre"]]
movie_names_and_genres

     Movie Name      Genre
0       Movie 1     Sci-Fi
1       Movie 2  Adventure
2       Movie 3    Romance
3       Movie 4    Romance
4       Movie 5     Action
..          ...        ...
995   Movie 996     Sci-Fi
996   Movie 997  Adventure
997   Movie 998    Fantasy
998   Movie 999     Action
999  Movie 1000     Horror

[1000 rows x 2 columns]

## 5. Select movies released between 1990 and 2010

In [29]:
movies_1990_to_2010 = df[df["Release_Year"].between(1990, 2010)]
movies_1990_to_2010

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1     Sci-Fi          2000          6.0  1680.53
1       Movie 2  Adventure          2000          2.2   987.24
2       Movie 3    Romance          2002          5.2  1122.13
3       Movie 4    Romance          2001          4.5   581.84
5       Movie 6    Fantasy          1997          2.4   485.22
..          ...        ...           ...          ...      ...
991   Movie 992   Thriller          2004          9.2   251.25
994   Movie 995     Sci-Fi          1997          2.0   342.98
996   Movie 997  Adventure          1993          6.2  1255.27
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[500 rows x 5 columns]

## 6. Count the number of movies in each genre

In [30]:
movies_per_genre = df["Genre"].value_counts().rename("Movie Count")
movies_per_genre

Genre
Drama        113
Comedy       110
Fantasy      107
Thriller     107
Action       104
Adventure     96
Sci-Fi        93
Romance       91
Horror        90
Mystery       89
Name: Movie Count, dtype: int64

## 7. Find the highest IMDb-rated movie

In [31]:
highest_rated_movie = df.loc[[df["IMDb_Rating"].idxmax()]]
highest_rated_movie

    Movie Name    Genre  Release_Year  IMDb_Rating  Revenue
106  Movie 107  Romance          2007         10.0  1837.45

## 8. Find the average IMDb rating of all movies

In [32]:
average_imdb_rating = df["IMDb_Rating"].mean()
print(f"Average IMDb rating: {average_imdb_rating:.2f}")

Average IMDb rating: 5.46

## 9. Find the total box-office collection of all movies

In [33]:
total_box_office = df["Revenue"].sum()
print(f"Total box-office collection: {total_box_office:,.2f}")

Total box-office collection: 1,049,716.26

## 10. Select movies with box-office earnings greater than 500 million

In [34]:
movies_over_500_million = df[df["Revenue"] > 500]
movies_over_500_million

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1     Sci-Fi          2000          6.0  1680.53
1       Movie 2  Adventure          2000          2.2   987.24
2       Movie 3    Romance          2002          5.2  1122.13
3       Movie 4    Romance          2001          4.5   581.84
4       Movie 5     Action          2012          6.6  1205.51
..          ...        ...           ...          ...      ...
993   Movie 994  Adventure          1989          7.3  1273.65
996   Movie 997  Adventure          1993          6.2  1255.27
997   Movie 998    Fantasy          2016          8.1  1161.96
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[774 rows x 5 columns]

## 11. Rank movies based on IMDb rating

In [35]:
ranked_movies = df.assign(
    IMDb_Rank=df["IMDb_Rating"].rank(method="dense", ascending=False).astype(int)
).sort_values(["IMDb_Rank", "Movie Name"])
ranked_movies[["IMDb_Rank", "Movie Name", "IMDb_Rating", "Genre"]]

     IMDb_Rank Movie Name  IMDb_Rating      Genre
106          1  Movie 107         10.0    Romance
241          1  Movie 242         10.0     Comedy
472          1  Movie 473         10.0    Fantasy
564          1  Movie 565         10.0     Action
610          1  Movie 611         10.0    Mystery
..         ...        ...          ...        ...
577         91  Movie 578          1.0     Action
699         91  Movie 700          1.0   Thriller
758         91  Movie 759          1.0     Horror
80          91   Movie 81          1.0  Adventure
955         91  Movie 956          1.0  Adventure

[1000 rows x 4 columns]

## 12. Sort movies by release year in descending order

In [36]:
movies_by_latest_year = df.sort_values("Release_Year", ascending=False)
movies_by_latest_year

    Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
836  Movie 837      Drama          2024          5.6   913.15
827  Movie 828      Drama          2024          2.0   146.52
47    Movie 48  Adventure          2024          4.6  1630.30
909  Movie 910    Fantasy          2024          4.7  1251.35
907  Movie 908    Romance          2024          5.8  1821.62
..         ...        ...           ...          ...      ...
41    Movie 42   Thriller          1980          1.9  1882.34
551  Movie 552    Mystery          1980          8.3    40.79
174  Movie 175     Action          1980          2.1   793.29
170  Movie 171    Mystery          1980          4.6  1684.78
244  Movie 245      Drama          1980          1.3  1231.51

[1000 rows x 5 columns]

## 13. Find all duplicate movie names, if any

In [37]:
duplicate_movie_names = df[df["Movie Name"].duplicated(keep=False)].sort_values("Movie Name")
duplicate_movie_names

   Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
9    Movie 10      Drama          1996          3.2  1352.66
12   Movie 10      Drama          1996          3.2  1352.66
10   Movie 11    Mystery          2003          6.3   596.43
13   Movie 11    Mystery          2003          6.3   596.43
11   Movie 12     Sci-Fi          1988          3.0  1134.01
14   Movie 12     Sci-Fi          1988          3.0  1134.01
15   Movie 16     Comedy          2006          2.3  1322.79
20   Movie 16     Comedy          2006          2.3  1322.79
16   Movie 17     Horror          2007          6.2  1114.31
21   Movie 17     Horror          2007          6.2  1114.31
17   Movie 18  Adventure          1998          7.9  1426.73
22   Movie 18  Adventure          1998          7.9  1426.73
18   Movie 19     Comedy          1986          6.0  1783.44
23   Movie 19     Comedy          1986          6.0  1783.44
19   Movie 20    Fantasy          1982          6.9  1598.08
24   Movie 20    Fantasy          1982          6.9  1598.08

## 14. Remove duplicate movie names

In [38]:
movies_without_duplicate_names = df.drop_duplicates(subset="Movie Name", keep="first").reset_index(drop=True)
print(f"Rows before: {len(df):,}")
print(f"Rows after removing duplicate names: {len(movies_without_duplicate_names):,}")
movies_without_duplicate_names

Rows before: 1,000
Rows after removing duplicate names: 992

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1     Sci-Fi          2000          6.0  1680.53
1       Movie 2  Adventure          2000          2.2   987.24
2       Movie 3    Romance          2002          5.2  1122.13
3       Movie 4    Romance          2001          4.5   581.84
4       Movie 5     Action          2012          6.6  1205.51
..          ...        ...           ...          ...      ...
987   Movie 996     Sci-Fi          2013          8.7   456.39
988   Movie 997  Adventure          1993          6.2  1255.27
989   Movie 998    Fantasy          2016          8.1  1161.96
990   Movie 999     Action          1996          8.9   941.67
991  Movie 1000     Horror          1995          9.4  1390.70

[992 rows x 5 columns]

## 15. Replace Sci-Fi genre with Science Fiction

In [39]:
movies_with_updated_genre = df.copy()
movies_with_updated_genre["Genre"] = movies_with_updated_genre["Genre"].replace({"Sci-Fi": "Science Fiction"})
movies_with_updated_genre

     Movie Name            Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1  Science Fiction          2000          6.0  1680.53
1       Movie 2        Adventure          2000          2.2   987.24
2       Movie 3          Romance          2002          5.2  1122.13
3       Movie 4          Romance          2001          4.5   581.84
4       Movie 5           Action          2012          6.6  1205.51
..          ...              ...           ...          ...      ...
995   Movie 996  Science Fiction          2013          8.7   456.39
996   Movie 997        Adventure          1993          6.2  1255.27
997   Movie 998          Fantasy          2016          8.1  1161.96
998   Movie 999           Action          1996          8.9   941.67
999  Movie 1000           Horror          1995          9.4  1390.70

[1000 rows x 5 columns]

## 16. Select the first 10 movies

In [40]:
first_10_movies = df.head(10)
first_10_movies

  Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0    Movie 1     Sci-Fi          2000          6.0  1680.53
1    Movie 2  Adventure          2000          2.2   987.24
2    Movie 3    Romance          2002          5.2  1122.13
3    Movie 4    Romance          2001          4.5   581.84
4    Movie 5     Action          2012          6.6  1205.51
5    Movie 6    Fantasy          1997          2.4   485.22
6    Movie 7    Mystery          2021          5.1  1683.99
7    Movie 8     Comedy          2005          4.0  1062.13
8    Movie 9     Horror          1992          2.8  1592.74
9   Movie 10      Drama          1996          3.2  1352.66

## 17. Select the last 5 movies

In [41]:
last_5_movies = df.tail(5)
last_5_movies

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
995   Movie 996     Sci-Fi          2013          8.7   456.39
996   Movie 997  Adventure          1993          6.2  1255.27
997   Movie 998    Fantasy          2016          8.1  1161.96
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

## 18. Group movies by genre and find the average IMDb rating for each genre

In [42]:
average_rating_by_genre = (
    df.groupby("Genre", as_index=False)["IMDb_Rating"]
      .mean()
      .rename(columns={"IMDb_Rating": "Average IMDb Rating"})
      .sort_values("Average IMDb Rating", ascending=False)
)
average_rating_by_genre

       Genre  Average IMDb Rating
7    Romance             5.938462
5     Horror             5.814444
6    Mystery             5.778652
0     Action             5.670192
8     Sci-Fi             5.445161
2     Comedy             5.442727
9   Thriller             5.267290
4    Fantasy             5.200000
3      Drama             5.173451
1  Adventure             5.012500

## 19. Find the number of movies released in each year

In [43]:
movies_per_year = (
    df.groupby("Release_Year")
      .size()
      .rename("Movie Count")
      .reset_index()
      .sort_values("Release_Year")
)
movies_per_year

    Release_Year  Movie Count
0           1980           26
1           1981           17
2           1982           21
3           1983           16
4           1984           16
5           1985           28
6           1986           21
7           1987           17
8           1988           20
9           1989           30
10          1990           21
11          1991           21
12          1992           26
13          1993           21
14          1994           23
15          1995           27
16          1996           26
17          1997           22
18          1998           29
19          1999           25
20          2000           29
21          2001           23
22          2002           24
23          2003           25
24          2004           20
25          2005           21
26          2006           23
27          2007           29
28          2008           24
29          2009           21
30          2010           20
31          2011           23
32          2012           20
33          2013           26
34          2014           20
35          2015           23
36          2016           14
37          2017           18
38          2018           18
39          2019           15
40          2020           20
41          2021           16
42          2022           25
43          2023           18
44          2024           32

## 20. Find the total box-office collection per genre

In [44]:
box_office_by_genre = (
    df.groupby("Genre", as_index=False)["Revenue"]
      .sum()
      .rename(columns={"Revenue": "Total Box Office Collection"})
      .sort_values("Total Box Office Collection", ascending=False)
)
box_office_by_genre

       Genre  Total Box Office Collection
2     Comedy                    122686.63
3      Drama                    120311.32
9   Thriller                    112412.12
0     Action                    111137.94
4    Fantasy                    109849.86
1  Adventure                    103864.42
6    Mystery                     98832.93
7    Romance                     94413.72
5     Horror                     90395.52
8     Sci-Fi                     85811.80

## Summary

The notebook demonstrates filtering, column selection, sorting, ranking, duplicate handling, replacement, aggregation, grouping, and summary statistics with Pandas.