# Pandas Practice

In [27]:
import os 
os.getcwd()

'c:\\Users\\MAHESH\\Desktop\\fullstack-python-training'

In [28]:
import pandas as pd
df = pd.read_csv("c:\\Users\\MAHESH\\Desktop\\fullstack-python-training\\movies.csv")
print(df.head())

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

In [25]:
df = pd.read_excel(
    r"c:\Users\MAHESH\Desktop\fullstack-python-training\Movies_Dataset.xlsx"
)
print(df.head())

  Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0    Movie 1     Sci-Fi          2000          6.0  1680.53
1    Movie 2  Adventure          2000          2.2   987.24
2    Movie 3    Romance          2002          5.2  1122.13
3    Movie 4    Romance          2001          4.5   581.84
4    Movie 5     Action          2012          6.6  1205.51

In [42]:
print(df.columns.tolist())

['movieId', 'title', 'genres']

In [29]:
# Select all movies in the "Action" genre. 
action_movies = df[df["genres"].str.contains("Action", na=False)]
action_movies

,movieId,title,genres
5,6,Heat (1995),Action|Crime|Thriller
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
14,15,Cutthroat Island (1995),Action|Adventure|Romance
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller
...,...,...,...
10289,139920,Women of the Prehistoric Planet (1966),Action|Adventure|Sci-Fi
10294,140711,American Ultra (2015),Action|Comedy
10297,140737,The Lost Room (2006),Action|Fantasy|Mystery
10310,142550,Ryuzo and the Seven Henchmen (2015),Action|Comedy
10318,143882,Operator (2015),Action|Drama|Thriller

In [30]:
crime=df[df["genres"].str.contains("Crime", na=False)]
crime

,movieId,title,genres
5,6,Heat (1995),Action|Crime|Thriller
15,16,Casino (1995),Crime|Drama
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller
20,21,Get Shorty (1995),Comedy|Crime|Thriller
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller
...,...,...,...
10259,135456,Ghost in the Shell: Stand Alone Complex - The ...,Action|Animation|Crime|Sci-Fi
10266,136018,Black Mass (2015),Crime|Drama
10267,136020,Spectre (2015),Action|Adventure|Crime
10287,139644,Sicario (2015),Crime|Drama|Mystery
10304,141688,Legend (2015),Crime|Thriller

In [31]:
# Select movies released after 2000
filter_movies = df[release_year > 2000]
filter_movies

,movieId,title,genres
3196,4052,Antitrust (2001),Crime|Drama|Thriller
3197,4053,Double Take (2001),Action|Comedy
3198,4054,Save the Last Dance (2001),Drama|Romance
3200,4056,"Pledge, The (2001)",Crime|Drama|Mystery|Thriller
3209,4068,Sugar & Spice (2001),Comedy
...,...,...,...
10323,146656,Creed (2015),Drama
10324,146684,Cosmic Scrat-tastrophe (2015),Animation|Children|Comedy
10326,148238,A Very Murray Christmas (2015),Comedy
10327,148626,The Big Short (2015),Drama
10328,149532,Marco Polo: One Hundred Eyes (2015),(no genres listed)

In [41]:
print(df.columns.tolist())

['movieId', 'title', 'genres']

In [47]:
# Select only "Movie Name" and "Genre" columns
selecte_c = df[["title", "genres"]]
selecte_c
selecte_c

,title,genres
0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,Jumanji (1995),Adventure|Children|Fantasy
2,Grumpier Old Men (1995),Comedy|Romance
3,Waiting to Exhale (1995),Comedy|Drama|Romance
4,Father of the Bride Part II (1995),Comedy
...,...,...
10324,Cosmic Scrat-tastrophe (2015),Animation|Children|Comedy
10325,Le Grand Restaurant (1966),Comedy
10326,A Very Murray Christmas (2015),Comedy
10327,The Big Short (2015),Drama
10328,Marco Polo: One Hundred Eyes (2015),(no genres listed)

In [49]:
# Select movies with an IMDb rating greater than 8.5.
if "IMDb_Rating" not in df.columns:
    print("IMDb_Rating column is not available in df.")
    print("Available columns:", df.columns.tolist())
    high_rated_movies = pd.DataFrame()
else:
    high_rated_movies = df[df["IMDb_Rating"] > 8.5]

high_rated_movies
high_rated_movies

IMDb_Rating column is not available in df.
Available columns: ['movieId', 'title', 'genres']

Empty DataFrame
Columns: []
Index: []

In [51]:
#Select movies released between 1990 and 2010
movies_bt = df[release_year.between(1990, 2010)]
movies_bt

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
10293,140265,George Carlin: Jammin' in New York (1992),Comedy
10297,140737,The Lost Room (2006),Action|Fantasy|Mystery
10301,141305,Round Trip to Heaven (1992),(no genres listed)
10314,143031,Jump In! (2007),Comedy|Drama|Romance
10317,143709,The Take (2009),(no genres listed)

In [53]:
genre_counts = (
    df["genres"]
    .str.split("|")
    .explode()
    .value_counts()
)

genre_counts

genres
Drama                 5220
Comedy                3515
Thriller              2187
Romance               1788
Action                1737
Crime                 1440
Adventure             1164
Horror                1001
Sci-Fi                 860
Mystery                675
Fantasy                670
Children               540
War                    503
Documentary            415
Musical                409
Animation              401
Western                235
Film-Noir              195
IMAX                   152
(no genres listed)       7
Name: count, dtype: int64

In [57]:
#Find the highest IMDb-rated movie. 
highest_rated_movie_row = df.loc[df["IMDb_Rating"].idxmax()]
highest_rated_movie_row

KeyError: 'IMDb_Rating'

In [ ]:
# Find the average IMDb rating of all movies

IMDb rating data is not available in df.

In [59]:
box_office_columns = [
    column for column in df.columns
    if "box" in column.lower() or "collection" in column.lower()
]

if box_office_columns:
    total_box_office = df[box_office_columns[0]].sum()
    print("Total box office collection:", total_box_office)
else:
    print("No box-office collection column is available.")

No box-office collection column is available.